apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      nodePort: 30000
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: configs
              mountPath: /etc/nginx/
      volumes:
        - name: configs
          configMap: 
            name: nginx-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |-
    events {}
    http{
    resolver kube-dns.kube-system;
    server {
      server_name _;
      root /usr/share/nginx/html;
      location /healthz {
        return 200 "health status welcome";
      }
      # reverse proxy
      location ~^/frontend2(.*)$  {
        proxy_pass frontend.default.svc.cluster.local:80/$1;
      }

      # reverse proxy
      location /backend {
        proxy_pass dotnet-backend.default.svc.cluster.local:8081/mythaistar;
      }
    }
    }



