apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    io.kompose.service: frontend
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
  selector:
    io.kompose.service: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/backend-net: "true"
        io.kompose.service: frontend
    spec:
      containers:
        - image: devonfwmts_frontend:latest
          imagePullPolicy: Never
          name: angular
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
