apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mssql-volume
  name: mssql-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5000Mi
status: {}
